# (gosh i dislike yml.)

language: haxe

# for "haxelib run openfl setup" below.
sudo: required

os:
 - linux

# because haxe version 3.2.1 is what i have on my own laptop.
haxe:
 - "3.2.1"

# because neko version 2.1.0 is what i have on my own laptop.
neko: "2.1.0"

# empirically discovered from the echo below, whatever.
cache:
  directories:
  - /home/travis/haxe/lib

install:
 - export LOG_FILE=/tmp/log	
 - echo $(haxelib config)
 - if [ -e ${LOG_FILE} ] ; then rm ${LOG_FILE}; fi
 - travis_wait haxelib --always install flixel >> ${LOG_FILE}
 - travis_wait $(yes 'y' | haxelib --always run openfl setup >> ${LOG_FILE})
 - echo $(tail -100 ${LOG_FILE})

script:
 - cd Flixel && make build-neko



