language: haxe

os:
 - linux

# since 3.2.1 is what i have on my own laptop.
haxe:
 - "3.2.1"

cache:
  directories:
  - /usr/share/haxelib

install:
 - travis_wait haxelib install flixel > /dev/null
 - travis_wait haxelib run openfl setup > /dev/null
 - haxelib config

script:
 - cd Flixel && make build-neko



