# (gosh i dislike yml.)

language: haxe

# for "haxelib run openfl setup" below.
sudo: required

os:
 - linux

# all the versions below are based on my ubuntu 14.04 lts 64 bit laptop.

haxe:
 - "3.2.1"

neko: "2.1.0"

# empirically discovered from the echo below, whatever.
cache:
  directories:
  - /home/travis/haxe/lib

install:
 - export LOG_FILE=/tmp/log	
 - echo $(haxelib config)
 - if [ -e ${LOG_FILE} ] ; then rm ${LOG_FILE}; fi
 - travis_wait haxelib --always install flixel >> ${LOG_FILE}
 - travis_wait haxelib --always install hxmidilib >> ${LOG_FILE}
 - travis_wait $(yes 'y' | haxelib --always run openfl setup >> ${LOG_FILE})
 - haxelib --always set openfl 3.6.1
 - haxelib --always set lime 2.9.1
 - echo $(tail -100 ${LOG_FILE})

script:
 - cd Flixel && make build-neko



