# (gosh i dislike yml.)

language: haxe

os:
 - linux

# because haxe version 3.2.1 is what i have on my own laptop.
haxe:
 - "3.2.1"

# because neko version 2.1.0 is what i have on my own laptop.
neko: "2.1.0"

# empirically discovered from the echo below, whatever.
cache:
  directories:
  - /home/travis/haxe/lib

install:
 - echo $(haxelib config)
 - rm /tmp/log
 - travis_wait haxelib --always install flixel >> /tmp/log
 - travis_wait haxelib --alwyas run openfl setup > /tmp/log
 - echo $(cat /tmp/log)

script:
 - cd Flixel && make build-neko



