language: haxe

os:
 - linux

# since 3.2.1 is what i have on my own laptop.
haxe:
 - "3.2.1"

# empirically discovered from the echo below, whatever.
cache:
  directories:
  - /home/travis/haxe/lib

install:
 - echo $(haxelib config)
 - travis_wait haxelib install flixel > /dev/null
 - travis_wait haxelib run openfl setup > /dev/null

script:
 - cd Flixel && make build-neko



