clean:
	rm -rf export/*

build-neko:
	openfl build neko

run-neko:
	openfl test neko

build-html5:
	openfl build html5

run-html5:
	openfl test html5

#com/obfusco/hxspin/spinmode/SpinModes.hx: ./spinmodes.py
#	./spinmodes.py
